print("what is your name human?")
name = input()
print(f"How old are you (in years)?")
user_age = int(input())
print(f"How tall are you (in meters)?")
user_height = float(input())
print(f"How much do you weigh (in kilograms)?")
user_weight = int(input())
user_bmi = round(user_weight / (user_height * user_height), 2)
print(f"{name} you are {user_age} years old and your BMI is {user_bmi}")
